apiVersion: v1
kind: Pod
metadata:
  name: cpu-test-nginx
spec:
  containers:
  - name: nginx-stress
    image: debian
    command: ["/bin/bash", "-c"]
    args:
      - apt update && apt install -y nginx stress procps && 
        echo "Starting NGINX..." && 
        nginx && 
        echo "Starting CPU stress test..." && 
        stress --cpu 4 &
        tail -f /dev/null
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: "100m"
